<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>

    <Description>NLog Target that emits the log entries to a fluentd node</Description>
    <Authors>Moriyoshi Koizumi, Jarred Capellman</Authors>
    <CurrentYear>$([System.DateTime]::Now.ToString(yyyy))</CurrentYear>
    <Copyright>Copyright (c) 2020 - Moriyoshi Koizumi and Jarred Capellman</Copyright>

    <Version>1.0.6.0</Version>

    <PackageTags>NLog;fluentd;log;logging</PackageTags>
    <PackageIconUrl>http://nlog-project.org/N.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/jcapellman/NLog.Targets.Fluentd</PackageProjectUrl>
    <PackageLicenseUrl>https://raw.githubusercontent.com/fluent/NLog.Targets.Fluentd/master/LICENSE.txt</PackageLicenseUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>git://github.com/jcapellman/NLog.Targets.Fluentd</RepositoryUrl>
    <PackageReleaseNotes>Add exclude properties property</PackageReleaseNotes>
    <PackageId>NLog.Targets.Fluentd.NetStandard</PackageId>
    <Product>NLog.Targets.Fluentd.NetStandard</Product>
    <Company>Moriyoshi Koizumi, Jarred Capellman</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MsgPack.Cli" Version="1.0.1" />
    <PackageReference Include="NLog" Version="4.7.0" />
  </ItemGroup>
</Project>